version: '3.8'

services:
  web:
    image: hvidigaljr/zobot-top:latest
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.zobot-top.rule=Host(`zobot.top`)
        - traefik.http.routers.zobot-top.entrypoints=websecure
        - traefik.http.routers.zobot-top.tls.certresolver=letsencryptresolver
        - traefik.http.services.zobot-top.loadbalancer.server.port=3000
        - traefik.http.services.zobot-top.loadbalancer.passHostHeader=true
        - traefik.http.routers.zobot-top.service=zobot-top
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

networks:
  portainer:
    external: true
    name: portainer